apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: t7ujupz1a-nodejs-gitops
  description: This is GitOps manifest for t7ujupz1a-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=t7ujupz1a-nodejs
    backstage.io/kubernetes-id: t7ujupz1a-nodejs 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: t7ujupz1a-nodejs-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:t7ujupz1a-nodejs
